- hosts: all

  roles:
    - {role: geerlingguy.java, become: yes}
    - role: geerlingguy.jenkins
      jenkins_admin_username: admin
      jenkins_admin_password: admin
      jenkins_http_port: 9000
      jenkins_plugins:
        - git
        - ssh
        #- github
        - ansicolor
        - credentials
        - EnvInject
      become: yes
  vars:
    jenkins_ini: |-
      [jenkins]
      url=http://localhost:9000/

  tasks: 
    - name: Restart Jenkins again to ready plugins
      become: yes
      service:
        name: jenkins
        state: restarted

      # Make sure Jenkins is ready to run after last restart
    - name: Ensure Jenkins is up and running
      uri:
        url: http://localhost:9000
        status_code: 200
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 60
      delay: 5
      until: >
        'status' in jenkins_service_status and
        jenkins_service_status['status'] == 200

    - name: install maven
      apt: pkg="maven" state="present"
      become: yes

    - name: Install jenkins job builder
      pip: name=jenkins-job-builder extra_args=--user executable=/usr/bin/pip

    - name: Copy jenkins.ini
      copy: content="{{jenkins_ini}}" dest=/etc/jenkins_jobs.ini
      become: yes

    - name: Update jenkins job
      command: .local/bin/jenkins-jobs --conf /etc/jenkins_jobs.ini --user admin --password admin update ~/job.yml



    # If cross-site projection enabled:
    #  - uri:
    #      url: 'http://127.0.0.1:9000/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    #      user: admin
    #      password: admin
    #      force_basic_auth: yes
    #      return_content: yes
    #    register: crumb

    - uri:
        method: POST
        url: 'http://127.0.0.1:9000/credentials/store/system/domain/_/createCredentials'
        user: admin
        password: admin
        force_basic_auth: yes
#        headers:
#          Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
        body: |
          json={
              "": "0",
              "credentials": {
                "scope": "GLOBAL",
                "id": "gitCredId",
                "username": "{{git_user}}",
                "password": "{{git_password}}",
                "description": "Github Enterprise password",
                "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
              }
            }
      register: result  
      failed_when: result.status not in [200,302]